name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami

      # - name: Deploy to DigitalOcean
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DIGITALOCEAN_HOST }}
      #     username: ${{ secrets.DIGITALOCEAN_USERNAME }}
      #     key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
      #     script: |
      #       # Update and restart your Python script
      #       cd /path/to/your/script
      #       git pull
      #       # Restart your Python script (e.g., using systemd or supervisor)
      #       sudo systemctl restart your-script